FROM golang:1.20

WORKDIR /client

COPY . ./

# Build Go model
RUN CGO_ENABLED=0 go build -o ./bin/client_func ./client/

FROM alpine:3.18

COPY --from=0  /client/bin/client_func /client_func

COPY /certs /app/certs

ENTRYPOINT ["./client_func"]